import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex justify-center items-center py-4 px-10 bg-white mx-auto mt-8 mb-12 w-fit">
          <a href="/" className="font-light text-lg text-gray-900 transition-colors px-4 !no-underline">Decks</a>
          <span className="text-gray-300 text-xl font-light select-none">|</span>
          <a href="/practice" className="font-light text-lg text-gray-900 transition-colors px-4 !no-underline">AI Practice</a>
        </nav>
        {children}
      </body>
    </html>
  );
}
